"""Parametric axisymmetric CFT/HEMP geometry workstream."""

from .adapters import (
    GeometryAdapter,
    GeometryRegionProvider,
    L1aCurrentEquivalentPreview,
    SolverNeutralGeometryContract,
    to_l1a_current_equivalent_preview,
    to_magnetics_handoff,
)
from .descriptors import (
    GeometryDescriptors,
    compute_descriptors,
    geometry_with_design_vector,
)
from .export import (
    ARTIFACT_CLAIM_LIMIT,
    ARTIFACT_GENERATOR_ID,
    ARTIFACT_GENERATOR_VERSION,
    LoadedArtifactBundle,
    VIEWER_SCHEMA_VERSION,
    load_artifact_bundle,
    svg_meridional_cross_section,
    viewer_data,
    write_reference_artifacts,
)
from .generators import (
    PPMStackParameters,
    compact_high_gradient_stack,
    divergent_exit_stack,
    generate_twt_inspired_ppm_stack,
    historical_envelope_baseline,
    reference_variants,
)
from .model import (
    CANONICALIZATION,
    SCHEMA_VERSION,
    AxisymmetricCFTGeometry,
    ChamberDefinition,
    ElectrodeDefinition,
    EvidenceNote,
    ExternalComponent,
    GeometryValidationError,
    MagnetizationDirection,
    ManufacturingRules,
    MaterialDefinition,
    MaterialKind,
    MeridionalRegion,
    PPMStage,
    PermanentMagnetAuthority,
    PermanentMagnetRepresentationPlan,
    RegionShape,
    canonical_json,
    deserialize_geometry,
    geometry_from_dict,
)
from .topology import InterfaceSurfaceDescriptor, interface_topology

__all__ = [
    "ARTIFACT_CLAIM_LIMIT",
    "ARTIFACT_GENERATOR_ID",
    "ARTIFACT_GENERATOR_VERSION",
    "CANONICALIZATION",
    "SCHEMA_VERSION",
    "VIEWER_SCHEMA_VERSION",
    "AxisymmetricCFTGeometry",
    "ChamberDefinition",
    "ElectrodeDefinition",
    "EvidenceNote",
    "ExternalComponent",
    "GeometryAdapter",
    "GeometryDescriptors",
    "GeometryRegionProvider",
    "GeometryValidationError",
    "InterfaceSurfaceDescriptor",
    "L1aCurrentEquivalentPreview",
    "LoadedArtifactBundle",
    "MagnetizationDirection",
    "ManufacturingRules",
    "MaterialDefinition",
    "MaterialKind",
    "MeridionalRegion",
    "PPMStackParameters",
    "PPMStage",
    "PermanentMagnetAuthority",
    "PermanentMagnetRepresentationPlan",
    "RegionShape",
    "SolverNeutralGeometryContract",
    "canonical_json",
    "compact_high_gradient_stack",
    "compute_descriptors",
    "deserialize_geometry",
    "divergent_exit_stack",
    "generate_twt_inspired_ppm_stack",
    "geometry_from_dict",
    "geometry_with_design_vector",
    "historical_envelope_baseline",
    "interface_topology",
    "load_artifact_bundle",
    "reference_variants",
    "svg_meridional_cross_section",
    "to_l1a_current_equivalent_preview",
    "to_magnetics_handoff",
    "viewer_data",
    "write_reference_artifacts",
]
