"""Verified prescribed-field kinetic-ion/fluid-electron hybrid first slice."""

from .checkpoint import (
    CHECKPOINT_SCHEMA_VERSION,
    TIME_INTEGRATION_CONTRACT,
    HybridCheckpoint,
    ProvenanceRecord,
    checkpoint_digest,
    load_checkpoint,
    save_checkpoint,
)
from .collisions import (
    collide_with_neutral_background,
    collision_frequency_per_s,
    collision_probability,
)
from .electrons import (
    FluidElectronClosure,
    IsothermalQuasineutralClosure,
    conservative_electron_exchange,
)
from .manufactured import ManufacturedRunResult, run_tiny_manufactured_case
from .models import (
    BOLTZMANN_CONSTANT_J_PER_K,
    ELEMENTARY_CHARGE_C,
    XENON_ATOM_MASS_KG,
    AxisAlignedBox,
    BorisStepResult,
    BoundaryPolicy,
    CartesianGrid1D,
    CollisionBatchResult,
    CollisionCrossSection,
    DepositedMoments,
    ElectronClosureResult,
    ElectronFluidState,
    HybridDeviceError,
    HybridError,
    HybridOptionalDependencyError,
    HybridValidationError,
    Particle,
    SourceExchange,
    UniformFields,
    VelocityTimeLevel,
    XE,
    XE_DOUBLE_PLUS,
    XE_PLUS,
    XenonSpecies,
)
from .reference import (
    BoundaryResult,
    advance_particles,
    apply_boundary,
    boris_push,
    boris_push_diagnosed,
    deposit_cic_periodic,
    initialize_leapfrog,
    particle_kinetic_energy,
    particle_momentum,
    synchronize_velocity,
)
from .rng import RNG_ALGORITHM, random_u64, random_uniform

__all__ = [
    "BOLTZMANN_CONSTANT_J_PER_K",
    "CHECKPOINT_SCHEMA_VERSION",
    "ELEMENTARY_CHARGE_C",
    "RNG_ALGORITHM",
    "TIME_INTEGRATION_CONTRACT",
    "XENON_ATOM_MASS_KG",
    "XE",
    "XE_DOUBLE_PLUS",
    "XE_PLUS",
    "AxisAlignedBox",
    "BorisStepResult",
    "BoundaryPolicy",
    "BoundaryResult",
    "CartesianGrid1D",
    "CollisionBatchResult",
    "CollisionCrossSection",
    "DepositedMoments",
    "ElectronClosureResult",
    "ElectronFluidState",
    "FluidElectronClosure",
    "HybridCheckpoint",
    "HybridDeviceError",
    "HybridError",
    "HybridOptionalDependencyError",
    "HybridValidationError",
    "IsothermalQuasineutralClosure",
    "ManufacturedRunResult",
    "Particle",
    "ProvenanceRecord",
    "SourceExchange",
    "UniformFields",
    "VelocityTimeLevel",
    "XenonSpecies",
    "advance_particles",
    "apply_boundary",
    "boris_push",
    "boris_push_diagnosed",
    "checkpoint_digest",
    "collide_with_neutral_background",
    "collision_frequency_per_s",
    "collision_probability",
    "conservative_electron_exchange",
    "deposit_cic_periodic",
    "initialize_leapfrog",
    "load_checkpoint",
    "particle_kinetic_energy",
    "particle_momentum",
    "random_u64",
    "random_uniform",
    "run_tiny_manufactured_case",
    "save_checkpoint",
    "synchronize_velocity",
]
