"""Robust, dependency-free field-to-plasma topology coupling."""

from .losses import derive_mirror_loss, loss_cone_probability
from .models import (
    AcceptedArtifactAdapter,
    AcceptedArtifactClaims,
    AcceptedFieldEvidence,
    AdapterVersionContract,
    AxisymmetricFieldMapLike,
    AxisymmetricProfileLike,
    CandidateKind,
    CouplingError,
    CouplingRecord as ScreeningProxyRecord,
    CouplingValidationError,
    EvidenceVerificationError,
    FieldProfile,
    FieldProvenance,
    MapValidationPolicy,
    MirrorLoss,
    PlateauPolicy,
    ProfileDescriptor,
    ProfileRole,
    SolverDiagnosticsEvidence,
    TiePolicy,
    TopologyCandidate,
    TopologyPolicy,
    TopologyResolutionError,
    TopologySegment,
    TopologyStatus,
    UncertainProbability,
    UncertaintyModel,
    ValidatedAxisymmetricMap,
)
from .profiles import (
    extract_profiles,
    interpolate_profile,
    stable_lerp,
    validate_uncertainty_model,
)
from .records import coupling_model_hash
from .screening_proxy import build_screening_proxy
from .topology import (
    describe_profile,
    locate_boundary_extrema,
    locate_extrema,
    locate_nulls,
)
from .validation import (
    canonical_axisymmetric_map_bytes,
    hash_axisymmetric_map,
    source_map_binding_hash,
    validate_axisymmetric_map,
    validate_profile,
    validate_provenance,
    verify_accepted_field_artifact,
)
from .surfaces import (
    bilinear_sample,
    certify_contour_field,
    magnetic_null_geometry,
    require_same_flux_surface,
    trace_flux_contours,
    validate_simple_contour,
)
from .v3_evidence import (
    AcceptedTopologyStabilityEvidence,
    AcceptedV3FieldEvidence,
    canonical_psi_map_bytes,
    hash_psi_map,
    reverify_v3_evidence,
    reverify_v3_topology_stability,
    v3_evidence_binding_hash,
    verify_v3_field_artifact,
    verify_v3_topology_stability,
)
from .v3_models import (
    AxisymmetricPsiFieldMapLike,
    BoundedMirrorProbability,
    BoundaryNullDiagnostic,
    CellRegistration,
    ContourFieldCertificate,
    ElectronAdiabaticInputs,
    FluxCell,
    FluxContour,
    FluxQuantileOutcome,
    FluxSurfaceMirror,
    FluxSurfacePolicy,
    StabilityCase,
    SurfaceStatus,
    TopologyStabilityStudy,
    V3ArtifactAdapter,
    V3ArtifactClaims,
    V3CouplingRecord,
    V3EvidenceIdentity,
    ValidatedPsiMap,
)
from .v3_records import (
    COUPLING_SCHEMA_VERSION as COUPLING_V3_SCHEMA_VERSION,
    build_coupling_record as build_closed_contour_record,
    coupling_record_dict as closed_contour_record_dict,
    global_solver_inputs as closed_contour_solver_inputs,
    verify_topology_stability,
)
from .records import COUPLING_SCHEMA_VERSION as COUPLING_V2_SCHEMA_VERSION
from .v4_evidence import (
    AcceptedV4MapSet,
    reverify_v4_map_set,
    v4_map_set_evidence_fingerprints,
    verify_v4_map_set,
)
from .v4_models import (
    AxialDominanceMetrics,
    AxialDominancePolicy,
    CFT_V4_DEVELOPMENT_MANIFEST,
    CFTCell,
    CFTCellRegistration,
    CFTGeometry,
    CFTStabilityPolicy,
    ClosedIslandDiagnostic,
    ElectronOrbitSample,
    FieldLineSeed,
    FieldLineTracePolicy,
    HeldOutCaseRegistration,
    HeldOutCaseOutcome,
    HeldOutValidationAdapter,
    HeldOutValidationClaims,
    HeldOutValidationIdentity,
    HeldOutValidationPolicy,
    HeldOutValidationRegistration,
    OrbitAssessment,
    OrbitVerificationAdapter,
    OrbitVerificationClaims,
    OrbitVerificationIdentity,
    SeedPathOutcome,
    V4CouplingRecord,
    V4Criterion,
    V4MapAssessment,
    V4StabilityAssessment,
    V4Status,
    WallConnectedMirrorPath,
    WallCusp,
    WallCuspPolicy,
    ValidationSetManifest,
    validation_set_manifest_hash,
)
from .v4_records import (
    AcceptedCFTProjection,
    COUPLING_V4_SCHEMA_VERSION,
    accept_cft_projection,
    build_cft_coupling_record,
    cft_coupling_record_dict,
    cft_preregistration_hash,
    cft_solver_inputs,
)
from .v4_validation import (
    AcceptedHeldOutValidationEvidence,
    reverify_held_out_validation,
    verify_held_out_validation,
)

COUPLING_SCHEMA_VERSION = COUPLING_V4_SCHEMA_VERSION
build_coupling_record = build_cft_coupling_record
coupling_record_dict = cft_coupling_record_dict
global_solver_inputs = cft_solver_inputs

__all__ = [
    "COUPLING_SCHEMA_VERSION",
    "COUPLING_V2_SCHEMA_VERSION",
    "COUPLING_V3_SCHEMA_VERSION",
    "COUPLING_V4_SCHEMA_VERSION",
    "AcceptedArtifactAdapter",
    "AcceptedArtifactClaims",
    "AcceptedFieldEvidence",
    "AdapterVersionContract",
    "AxisymmetricFieldMapLike",
    "AxisymmetricProfileLike",
    "CandidateKind",
    "CouplingError",
    "ScreeningProxyRecord",
    "CouplingValidationError",
    "EvidenceVerificationError",
    "FieldProfile",
    "FieldProvenance",
    "MapValidationPolicy",
    "MirrorLoss",
    "PlateauPolicy",
    "ProfileDescriptor",
    "ProfileRole",
    "SolverDiagnosticsEvidence",
    "TiePolicy",
    "TopologyCandidate",
    "TopologyPolicy",
    "TopologyResolutionError",
    "TopologySegment",
    "TopologyStatus",
    "UncertainProbability",
    "UncertaintyModel",
    "ValidatedAxisymmetricMap",
    "AcceptedV3FieldEvidence",
    "AcceptedV4MapSet",
    "AcceptedCFTProjection",
    "AcceptedHeldOutValidationEvidence",
    "AcceptedTopologyStabilityEvidence",
    "AxisymmetricPsiFieldMapLike",
    "BoundedMirrorProbability",
    "BoundaryNullDiagnostic",
    "CellRegistration",
    "ContourFieldCertificate",
    "ElectronAdiabaticInputs",
    "FluxCell",
    "FluxContour",
    "FluxQuantileOutcome",
    "FluxSurfaceMirror",
    "FluxSurfacePolicy",
    "StabilityCase",
    "SurfaceStatus",
    "TopologyStabilityStudy",
    "V3ArtifactAdapter",
    "V3ArtifactClaims",
    "V3CouplingRecord",
    "V3EvidenceIdentity",
    "ValidatedPsiMap",
    "build_coupling_record",
    "build_cft_coupling_record",
    "build_closed_contour_record",
    "build_screening_proxy",
    "bilinear_sample",
    "certify_contour_field",
    "canonical_psi_map_bytes",
    "canonical_axisymmetric_map_bytes",
    "coupling_model_hash",
    "coupling_record_dict",
    "cft_coupling_record_dict",
    "cft_preregistration_hash",
    "closed_contour_record_dict",
    "derive_mirror_loss",
    "describe_profile",
    "extract_profiles",
    "global_solver_inputs",
    "cft_solver_inputs",
    "accept_cft_projection",
    "closed_contour_solver_inputs",
    "hash_axisymmetric_map",
    "hash_psi_map",
    "interpolate_profile",
    "locate_boundary_extrema",
    "locate_extrema",
    "locate_nulls",
    "loss_cone_probability",
    "magnetic_null_geometry",
    "require_same_flux_surface",
    "reverify_v3_evidence",
    "reverify_v3_topology_stability",
    "source_map_binding_hash",
    "stable_lerp",
    "trace_flux_contours",
    "validate_simple_contour",
    "validate_axisymmetric_map",
    "validate_profile",
    "validate_provenance",
    "validate_uncertainty_model",
    "verify_accepted_field_artifact",
    "verify_topology_stability",
    "verify_v3_field_artifact",
    "verify_v3_topology_stability",
    "v3_evidence_binding_hash",
    "verify_v4_map_set",
    "v4_map_set_evidence_fingerprints",
    "reverify_v4_map_set",
    "AxialDominanceMetrics",
    "AxialDominancePolicy",
    "CFT_V4_DEVELOPMENT_MANIFEST",
    "CFTCell",
    "CFTCellRegistration",
    "CFTGeometry",
    "CFTStabilityPolicy",
    "ClosedIslandDiagnostic",
    "ElectronOrbitSample",
    "FieldLineSeed",
    "FieldLineTracePolicy",
    "HeldOutCaseRegistration",
    "HeldOutCaseOutcome",
    "HeldOutValidationAdapter",
    "HeldOutValidationClaims",
    "HeldOutValidationIdentity",
    "HeldOutValidationPolicy",
    "HeldOutValidationRegistration",
    "OrbitAssessment",
    "OrbitVerificationAdapter",
    "OrbitVerificationClaims",
    "OrbitVerificationIdentity",
    "SeedPathOutcome",
    "V4CouplingRecord",
    "V4Criterion",
    "V4MapAssessment",
    "V4StabilityAssessment",
    "V4Status",
    "WallConnectedMirrorPath",
    "WallCusp",
    "WallCuspPolicy",
    "ValidationSetManifest",
    "validation_set_manifest_hash",
    "verify_held_out_validation",
    "reverify_held_out_validation",
]
