"""L1a axisymmetric magnetostatic equivalent-current solver."""

from .artifacts import (
    ARTIFACT_SCHEMA_VERSION,
    MANIFEST_SCHEMA_VERSION,
    canonical_payload_sha256,
    design_manifest,
    field_artifact,
    manifest_entry,
    validate_design_manifest,
    validate_design_manifest_file,
    validate_field_artifact,
    validate_field_artifact_file,
    write_design_manifest,
    write_field_artifact,
)
from .models import (
    MU0_H_PER_M,
    AxisymmetricDomain,
    AxisymmetricProblem,
    AzimuthalCurrentBand,
    FieldArtifactValidationError,
    FieldConvergenceError,
    FieldDeviceError,
    FieldError,
    FieldMap,
    FieldValidationError,
    SolverConfig,
    SolverDiagnostics,
    resolved_span_in_grid_spacings,
    span_meets_minimum_grid_spacings,
)
from .numerics import (
    current_density_grid,
    solve_problem_cpu,
    source_discretization_diagnostics,
)
from .verification import (
    ConvergenceReport,
    ManufacturedErrors,
    manufactured_values,
    max_field_difference,
    run_manufactured_convergence,
)
from .warp_solver import device_available, solve_problem_warp

__all__ = [
    "ARTIFACT_SCHEMA_VERSION",
    "MANIFEST_SCHEMA_VERSION",
    "MU0_H_PER_M",
    "AxisymmetricDomain",
    "AxisymmetricProblem",
    "AzimuthalCurrentBand",
    "ConvergenceReport",
    "FieldConvergenceError",
    "FieldArtifactValidationError",
    "FieldDeviceError",
    "FieldError",
    "FieldMap",
    "FieldValidationError",
    "ManufacturedErrors",
    "SolverConfig",
    "SolverDiagnostics",
    "canonical_payload_sha256",
    "current_density_grid",
    "design_manifest",
    "device_available",
    "field_artifact",
    "manifest_entry",
    "manufactured_values",
    "max_field_difference",
    "run_manufactured_convergence",
    "resolved_span_in_grid_spacings",
    "solve_problem_cpu",
    "solve_problem_warp",
    "source_discretization_diagnostics",
    "span_meets_minimum_grid_spacings",
    "validate_design_manifest",
    "validate_design_manifest_file",
    "validate_field_artifact",
    "validate_field_artifact_file",
    "write_design_manifest",
    "write_field_artifact",
]
