"""Independent multi-fidelity active-learning and uncertainty tools."""

from .acquisition import (
    AcquisitionWeights,
    CandidateScore,
    FidelityDecision,
    HighestFidelityQuota,
    PendingFantasyApproximation,
    approximate_pending_fantasization,
    score_candidate,
    select_fidelity,
)
from .calibration import (
    CalibrationDiagnostics,
    CoverageLevel,
    binomial_standard_error,
    coverage_diagnostics,
)
from .contracts import (
    ActiveLearningError,
    CampaignCounts,
    CampaignRecordAdapter,
    FidelitySource,
    GaussianConstraint,
    PosteriorAdapter,
    PosteriorPrediction,
)
from .robustness import (
    MonteCarloSummary,
    NormalTolerance,
    PromotionAssessment,
    ToleranceVariable,
    TriangularTolerance,
    UniformTolerance,
    assess_promotion,
    cvar,
    dominates,
    gaussian_feasibility_probability,
    propagate_monte_carlo,
    quantile,
)
from .stopping import (
    StoppingDecision,
    StoppingEvidence,
    StoppingPolicyV14,
    evaluate_stopping_gates,
)
from .uncertainty import (
    DiscrepancyEstimate,
    VarianceDecomposition,
    bias_correct_prediction,
    decompose_prediction,
    estimate_additive_discrepancy,
)

__all__ = [
    "AcquisitionWeights",
    "ActiveLearningError",
    "CalibrationDiagnostics",
    "CampaignCounts",
    "CampaignRecordAdapter",
    "CandidateScore",
    "CoverageLevel",
    "DiscrepancyEstimate",
    "FidelityDecision",
    "FidelitySource",
    "GaussianConstraint",
    "HighestFidelityQuota",
    "MonteCarloSummary",
    "NormalTolerance",
    "PendingFantasyApproximation",
    "PosteriorAdapter",
    "PosteriorPrediction",
    "PromotionAssessment",
    "StoppingDecision",
    "StoppingEvidence",
    "StoppingPolicyV14",
    "ToleranceVariable",
    "TriangularTolerance",
    "UniformTolerance",
    "VarianceDecomposition",
    "approximate_pending_fantasization",
    "assess_promotion",
    "bias_correct_prediction",
    "binomial_standard_error",
    "coverage_diagnostics",
    "cvar",
    "decompose_prediction",
    "dominates",
    "estimate_additive_discrepancy",
    "evaluate_stopping_gates",
    "gaussian_feasibility_probability",
    "propagate_monte_carlo",
    "quantile",
    "score_candidate",
    "select_fidelity",
]
