"""Sheath-closed four-cell power balance (v2) - DEVELOPMENT model.

Corrected Kornfeld ledger (R00-R26 reused read-only from ``cft_revival.plasma``,
R27 with the two proposed corrections so that it is an identity) plus
floating-dielectric sheath rows R28-R30, an anode row R31, declared potential
closure rows R32-R34 and cusp-loss rows R35-R37.  Nothing here is accepted
evidence and no thruster claim follows from it; see
``docs/workstreams/plasma-v2-formulation.md`` and
``spec/plasma_v2/four-cell-sheath-closure-v2.json``.
"""

from .constants import (
    CRITICAL_EMISSION_YIELD,
    FLOATING_SHEATH_COEFFICIENT,
    LEAK_WIDTH_PREFACTOR_RANGE,
    MASS_FLUX_RATIO,
    SPACE_CHARGE_LIMITED_COEFFICIENT,
)
from .manifold import (
    ReducedSolve,
    anode_row_residual_v,
    closure_probabilities,
    manifold_state,
    reduced_solve,
    sheath_drops,
)
from .models import (
    CUSP_PROBABILITY_ROWS,
    CURRENT_ROWS,
    POWER_ROWS,
    RESIDUAL_SIZE,
    ROW_IDS,
    STATE_SIZE,
    VOLTAGE_ROWS,
    AnodeRow,
    CuspEnergySplit,
    CuspLossClosure,
    CuspSheathSpec,
    FourthPotentialRow,
    PotentialClosure,
    PowerBalanceV2,
    RankReport,
    ResidualEvaluationV2,
    SheathClosureInputs,
    SheathClosureState,
    SheathMultiStartResult,
    SheathRegime,
    SheathSolveResult,
    SolverPolicy,
)
from .residuals import (
    MARGIN_NAMES,
    analytic_jacobian,
    constraint_margins,
    default_state_bounds,
    evaluate_residual,
    finite_difference_jacobian,
    hybrid_leak_width_m,
    is_feasible,
    matrix_rank,
    power_balance,
    raw_residual,
    residual_scales,
)
from .solver import (
    deterministic_initial_states,
    rank_report,
    representative_initial_state_v2,
    solve_sheath_closure,
    solve_sheath_closure_multistart,
)

__all__ = [
    "CRITICAL_EMISSION_YIELD",
    "CUSP_PROBABILITY_ROWS",
    "CURRENT_ROWS",
    "FLOATING_SHEATH_COEFFICIENT",
    "LEAK_WIDTH_PREFACTOR_RANGE",
    "MARGIN_NAMES",
    "MASS_FLUX_RATIO",
    "POWER_ROWS",
    "RESIDUAL_SIZE",
    "ROW_IDS",
    "SPACE_CHARGE_LIMITED_COEFFICIENT",
    "STATE_SIZE",
    "VOLTAGE_ROWS",
    "AnodeRow",
    "CuspEnergySplit",
    "CuspLossClosure",
    "CuspSheathSpec",
    "FourthPotentialRow",
    "PotentialClosure",
    "PowerBalanceV2",
    "RankReport",
    "ReducedSolve",
    "ResidualEvaluationV2",
    "SheathClosureInputs",
    "SheathClosureState",
    "SheathMultiStartResult",
    "SheathRegime",
    "SheathSolveResult",
    "SolverPolicy",
    "analytic_jacobian",
    "anode_row_residual_v",
    "closure_probabilities",
    "constraint_margins",
    "default_state_bounds",
    "deterministic_initial_states",
    "evaluate_residual",
    "finite_difference_jacobian",
    "hybrid_leak_width_m",
    "is_feasible",
    "manifold_state",
    "matrix_rank",
    "power_balance",
    "rank_report",
    "raw_residual",
    "reduced_solve",
    "representative_initial_state_v2",
    "residual_scales",
    "sheath_drops",
    "solve_sheath_closure",
    "solve_sheath_closure_multistart",
]
