"""Corrected, source-ledgered global xenon discharge model."""

from .models import (
    AnodeIonEnergySign,
    ConservationClosures,
    PlasmaError,
    PlasmaMultiStartResult,
    PlasmaNumericsError,
    PlasmaSolveResult,
    PlasmaState,
    PlasmaValidationError,
    PowerBalance,
    ResidualEvaluation,
    SolverDiagnostics,
    StateBounds,
    XenonGlobalInputs,
)
from .reference import (
    evaluate_plasma_residual_batch_cpu,
    evaluate_plasma_residual_cpu,
    solve_global_discharge_cpu,
    solve_global_discharge_multistart_cpu,
)
from .residuals import (
    analytic_jacobian,
    constraint_margins,
    default_state_bounds,
    finite_difference_jacobian,
    global_row_closed_form,
    is_feasible,
    potential_parametrized_state,
)
from .solver import (
    LeastSquaresResult,
    SolverOptions,
    deterministic_initial_states,
    project_nondecreasing,
    representative_initial_state,
    solve_bounded_least_squares,
    solve_global_discharge,
    solve_global_discharge_multistart,
)

__all__ = [
    "AnodeIonEnergySign",
    "ConservationClosures",
    "LeastSquaresResult",
    "PlasmaError",
    "PlasmaMultiStartResult",
    "PlasmaNumericsError",
    "PlasmaSolveResult",
    "PlasmaState",
    "PlasmaValidationError",
    "PowerBalance",
    "ResidualEvaluation",
    "SolverDiagnostics",
    "SolverOptions",
    "StateBounds",
    "XenonGlobalInputs",
    "analytic_jacobian",
    "constraint_margins",
    "default_state_bounds",
    "deterministic_initial_states",
    "evaluate_plasma_residual_batch_cpu",
    "evaluate_plasma_residual_cpu",
    "finite_difference_jacobian",
    "global_row_closed_form",
    "is_feasible",
    "potential_parametrized_state",
    "project_nondecreasing",
    "representative_initial_state",
    "solve_bounded_least_squares",
    "solve_global_discharge",
    "solve_global_discharge_cpu",
    "solve_global_discharge_multistart",
    "solve_global_discharge_multistart_cpu",
]
