"""Independent verified L3 electrostatic PIC-MCC foundation."""

from .adapters import LXCatParser, PICMIProblem, WarpXPICMIAdapter, lxcat_source_hash
from .collisions import CrossSectionTable, ElasticMCC, MCCDiagnostics
from .electrostatic import (
    ElectrostaticField,
    PeriodicPoisson1D,
    PoissonDiagnostics,
    PoissonSolver,
    add_uniform_background,
    charge_density_per_particle_c_per_m3,
    cic_deposit_charge,
    gather_cic,
    gather_face_cic,
    integrated_charge_c,
    physical_number_density_per_m3,
    represented_charge_c,
    scaled_l2,
)
from .models import (
    ELEMENTARY_CHARGE_C,
    EPSILON_0_F_PER_M,
    Grid1D,
    PICConfig,
    PICConvergenceError,
    PICDeviceError,
    PICError,
    PICValidationError,
    ParticleState,
    PoissonConfig,
    Species,
    StabilityReport,
    stability_report,
)
from .particles import boris_push_uniform, push_electrostatic_leapfrog
from .simulation import (
    PICStepper,
    PIC_CODE_REVISION,
    StepDiagnostics,
    field_energy_j,
    field_energy_j_per_m2,
    kinetic_energy_j,
    provenance_record,
    validate_checkpoint,
    write_checkpoint,
)
from .warp_backend import (
    WarpKernelResult,
    deposit_and_push_warp,
    device_available,
)

__all__ = [
    "ELEMENTARY_CHARGE_C",
    "EPSILON_0_F_PER_M",
    "CrossSectionTable",
    "ElasticMCC",
    "ElectrostaticField",
    "Grid1D",
    "LXCatParser",
    "MCCDiagnostics",
    "PICConfig",
    "PIC_CODE_REVISION",
    "PICConvergenceError",
    "PICDeviceError",
    "PICError",
    "PICMIProblem",
    "PICStepper",
    "PICValidationError",
    "ParticleState",
    "PeriodicPoisson1D",
    "PoissonConfig",
    "PoissonDiagnostics",
    "PoissonSolver",
    "Species",
    "StabilityReport",
    "StepDiagnostics",
    "WarpKernelResult",
    "WarpXPICMIAdapter",
    "add_uniform_background",
    "charge_density_per_particle_c_per_m3",
    "boris_push_uniform",
    "cic_deposit_charge",
    "deposit_and_push_warp",
    "device_available",
    "field_energy_j_per_m2",
    "field_energy_j",
    "gather_cic",
    "gather_face_cic",
    "integrated_charge_c",
    "kinetic_energy_j",
    "lxcat_source_hash",
    "provenance_record",
    "physical_number_density_per_m3",
    "push_electrostatic_leapfrog",
    "represented_charge_c",
    "stability_report",
    "scaled_l2",
    "validate_checkpoint",
    "write_checkpoint",
]
